version: '3.8'

services:
  # Production Frontend (Nginx serving built files)
  frontend-prod:
    build:
      context: ./Frontend-admin
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_BASE_URL: https://api.quizdash.dpdns.org
        VITE_WEBSOCKET_URL: wss://ws.quizdash.dpdns.org
        VITE_APP_NAME: QuizUP
        VITE_APP_VERSION: 1.0.0
    container_name: quizup_frontend_prod
    ports:
      - "5174:80"  # Different port for production
    networks:
      - quizup_network
    depends_on:
      - backend
      - matchserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    restart: unless-stopped

networks:
  quizup_network:
    external: true
