apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    uid: redis
    isDefault: false
    editable: true

  - name: WebSocket API
    type: golioth-websocket-datasource
    access: proxy
    url: ws://matchserver:3001
    uid: websocket
    isDefault: false
    editable: true
