apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

dashboards:
  - name: QuizUP Monitoring
    type: file
    folder: QuizUP
    options:
      path: /var/lib/grafana/dashboards
