groups:
  - name: capacity-and-latency
    interval: 30s
    rules:
      # Capacity: keep <= 3 matches per matchserver instance
      - alert: MatchServerCapacityBreachedWarning
        expr: matchserver_active_matches_total > 3
        for: 2m
        labels:
          severity: warning
          service: matchserver
        annotations:
          summary: "Match server over capacity (>3 matches)"
          description: "Instance {{ $labels.instance }} is running {{ $value }} active matches (>3)."

      - alert: MatchServerCapacityBreachedCritical
        expr: matchserver_active_matches_total > 3
        for: 5m
        labels:
          severity: critical
          service: matchserver
        annotations:
          summary: "Match server critically over capacity (>3 matches for 5m)"
          description: "Instance {{ $labels.instance }} remains above 3 active matches for over 5 minutes."

      # API p99 latency SLO (500ms)
      - alert: APIHighLatencyP99
        expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
          service: api-server
        annotations:
          summary: "High API p99 latency (>500ms)"
          description: "p99 latency is {{ $value }}s for 5m. Investigate slow endpoints, DB, or Redis."

      # Error rate > 5%
      - alert: APIHighErrorRate
        expr: (sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > 0.05
        for: 5m
        labels:
          severity: critical
          service: api-server
        annotations:
          summary: "API 5xx error rate > 5%"
          description: "5xx error rate exceeds 5% over the last 5 minutes."

      # Redis memory pressure (>80%)
      - alert: RedisMemoryHigh
        expr: (redis_memory_used_bytes / redis_total_system_memory_bytes) > 0.8
        for: 10m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory usage > 80%"
          description: "Redis memory usage is high (>80%). Consider adjusting eviction policy or scaling."

      # Postgres connections high (example threshold 80% of max)
      - alert: PostgresConnectionsHigh
        expr: pg_stat_activity_count > (pg_settings_max_connections * 0.8)
        for: 10m
        labels:
          severity: warning
          service: postgres
        annotations:
          summary: "Postgres connections > 80% of max"
          description: "Postgres active connections near limit. Current: {{ $value }}"
